/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.papermc.hangarpublishplugin

/**
 * A simple functional test for the 'io.papermc.hangarpublishplugin.greeting' plugin.
 */
class HangarPublishPluginFunctionalTest {

    /*
    @field:TempDir
    lateinit var projectDir: File

    private val buildFile by lazy { projectDir.resolve("build.gradle") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle") }

    @Test fun `can run task`() {
        // Set up the test build
        settingsFile.writeText("")
        buildFile.writeText("""
            plugins {
                id('io.papermc.hangarpublishplugin.greeting')
            }
        """.trimIndent())

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("greeting")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        // Verify the result
        assertTrue(result.output.contains("Hello from plugin 'io.papermc.hangarpublishplugin.greeting'"))
    }
     */
}
