/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.papermc.hangarpublishplugin

import org.gradle.api.Plugin
import org.gradle.api.Project

class HangarPublishPlugin : Plugin<Project> {
    override fun apply(project: Project) {
    }
}
