/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.papermc.hangarpublishplugin

/**
 * A simple unit test for the 'io.papermc.hangarpublishplugin.greeting' plugin.
 */
class HangarPublishPluginTest {

    /*
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("io.papermc.hangarpublishplugin.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
     */
}
